print("Welcome to the tip calculator!!")
total_bill = float(input("What was the total bill? "))
percent = int(input("What percentage tip you would like to give: 10%, 12%, or 15%? "))
people = int(input("How many people to split the bill? "))
pay = round((total_bill/people) + ((total_bill*percent)/100)/people,2)
print(f"Each person should pay {pay}")
